---
keys:
  - &hexa age1j3mkgedmeru63vwww6m44zfw09tg8yw6xdzstaq7ejfkvgcau40qwakm8x
  - &dasJ age1lz3mvem0rgfxj7uavth8du4xsw23wp5ts77m5vvclxyj5mjxfujs0jgtcz
  - &simon age17ez23w2kpxl0gcdx4ehcglkcfcfnv4qz0gq2n8ylxwx4yrtjpvjqxfasua
  - &cole-h age1m68dw9dltvtsg8e9lf5ts2vwnn4ykraguhjr8v65s0xessk3xqeqyz5jwt
  - &cole-h-2 age1nc9sh92wf62nt89k4vgyvqws2pt49cq6xqxx46jqpz4vqxsh5a4q8ltzp8
  - &zimbatm age1jrh8yyq3swjru09s75s4mspu0mphh7h6z54z946raa9wx3pcdegq0x8t4h
  - &core01-ofborg-org age1rrrj8tgcyp9xfxvy6zmk9487x62cgx0z68l7jretz2th6ey9nf4qh7nq7h
  - &eval01-ofborg-org age16d0phf8c5wy3rfsd4pgc42mqa3aw2llfukdhgu7pzklnzjr2rvxsusz842
  - &eval02-ofborg-org age1qn3q3y04pxumygmq96x0gk9qtrdcgdw4y5nl6xd780u4avk0qgsqy8tuu0
  - &eval03-ofborg-org age1yssfznyq8rljcpfthpulnvfls0l5t36fpqxkk5taxcwpkqhv9gcqrvvwh7
  - &eval04-ofborg-org age1vunut833rrdfulgnsjqtuke4yjtzexn2xqjqavwzxlgrg7n4y45qhurzwc
  - &build01-ofborg-org age1ulnex45wt7fpj92jy9c5del3ccz6mmnqptrsva24k8m7qsez9pcsdu3eae
  - &build02-ofborg-org age1wrp04f5c0d4jx3hwjsn8cyxdjzpzx6fl202zftqfvfdt7hx8efgskf6s86
  - &build03-ofborg-org age1n0yrvl2v397kztuhf00cdvrhf26c9uegwz6day8z9pyqj3zff4sq6ha0lm
  - &build04-ofborg-org age1l7xmxkh6y6d5svj06txknamlwdpfwac8855p3edgpu6jcqea7pvslw4r9a
  - &build05-ofborg-org age1mduqldqpqp33u2wwh685cwwkpj2ak36z67dtrq2tcskgqkultvps7w9q7u
  - &nixos-foundation-macstadium-44911305-ofborg-org age1x608lllmu7gdfjnn6c8mvmmguft5f22fu7g38wv3ckmzqy2usq0q5u2ekx
  - &nixos-foundation-macstadium-44911362-ofborg-org age1d0u5ukkwsf47x4jv6uklcc4j3ljnmyz879syya2qneagz0t42cqqyf09dt

creation_rules:
  - path_regex: non-critical-infra/secrets/[^/]+.core01.ofborg.org.yml
    key_groups:
      - age:
          - *core01-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/github-tokens.ofborg.org.yml
    key_groups:
      - age:
          - *core01-ofborg-org
          - *eval01-ofborg-org
          - *eval02-ofborg-org
          - *eval03-ofborg-org
          - *eval04-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/[^/]+.eval01.ofborg.org.yml
    key_groups:
      - age:
          - *eval01-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/[^/]+.eval02.ofborg.org.yml
    key_groups:
      - age:
          - *eval02-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/[^/]+.eval03.ofborg.org.yml
    key_groups:
      - age:
          - *eval03-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/[^/]+.eval04.ofborg.org.yml
    key_groups:
      - age:
          - *eval04-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/[^/]+.build01.ofborg.org.yml
    key_groups:
      - age:
          - *build01-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/[^/]+.build02.ofborg.org.yml
    key_groups:
      - age:
          - *build02-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/[^/]+.build03.ofborg.org.yml
    key_groups:
      - age:
          - *build03-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/[^/]+.build04.ofborg.org.yml
    key_groups:
      - age:
          - *build04-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: non-critical-infra/secrets/[^/]+.build05.ofborg.org.yml
    key_groups:
      - age:
          - *build05-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: macs/secrets/nixos-foundation-macstadium-44911305.yml
    key_groups:
      - age:
          - *nixos-foundation-macstadium-44911305-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: macs/secrets/nixos-foundation-macstadium-44911362.yml
    key_groups:
      - age:
          - *nixos-foundation-macstadium-44911362-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *cole-h
          - *cole-h-2
