---
keys:
  - &hexa age1j3mkgedmeru63vwww6m44zfw09tg8yw6xdzstaq7ejfkvgcau40qwakm8x
  - &dasJ age1lz3mvem0rgfxj7uavth8du4xsw23wp5ts77m5vvclxyj5mjxfujs0jgtcz
  - &cole-h age1m68dw9dltvtsg8e9lf5ts2vwnn4ykraguhjr8v65s0xessk3xqeqyz5jwt
  - &cole-h-2 age1nc9sh92wf62nt89k4vgyvqws2pt49cq6xqxx46jqpz4vqxsh5a4q8ltzp8
  - &zimbatm age1jrh8yyq3swjru09s75s4mspu0mphh7h6z54z946raa9wx3pcdegq0x8t4h
  - &core01-ofborg-org age1rrrj8tgcyp9xfxvy6zmk9487x62cgx0z68l7jretz2th6ey9nf4qh7nq7h
  - &eval01-ofborg-org age16d0phf8c5wy3rfsd4pgc42mqa3aw2llfukdhgu7pzklnzjr2rvxsusz842
  - &eval02-ofborg-org age1qn3q3y04pxumygmq96x0gk9qtrdcgdw4y5nl6xd780u4avk0qgsqy8tuu0
  - &eval03-ofborg-org age1yssfznyq8rljcpfthpulnvfls0l5t36fpqxkk5taxcwpkqhv9gcqrvvwh7
  - &eval04-ofborg-org age1vunut833rrdfulgnsjqtuke4yjtzexn2xqjqavwzxlgrg7n4y45qhurzwc
  - &build01-ofborg-org age1ulnex45wt7fpj92jy9c5del3ccz6mmnqptrsva24k8m7qsez9pcsdu3eae
  - &build02-ofborg-org age1wrp04f5c0d4jx3hwjsn8cyxdjzpzx6fl202zftqfvfdt7hx8efgskf6s86

creation_rules:
  - path_regex: secrets/[^/]+.core01.ofborg.org.yml
    key_groups:
      - age:
          - *core01-ofborg-org
          - *hexa
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: secrets/github-tokens.ofborg.org.yml
    key_groups:
      - age:
          - *core01-ofborg-org
          - *eval01-ofborg-org
          - *eval02-ofborg-org
          - *eval03-ofborg-org
          - *eval04-ofborg-org
          - *hexa
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: secrets/[^/]+.eval01.ofborg.org.yml
    key_groups:
      - age:
          - *eval01-ofborg-org
          - *hexa
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: secrets/[^/]+.eval02.ofborg.org.yml
    key_groups:
      - age:
          - *eval02-ofborg-org
          - *hexa
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: secrets/[^/]+.eval03.ofborg.org.yml
    key_groups:
      - age:
          - *eval03-ofborg-org
          - *hexa
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: secrets/[^/]+.eval04.ofborg.org.yml
    key_groups:
      - age:
          - *eval04-ofborg-org
          - *hexa
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: secrets/[^/]+.build01.ofborg.org.yml
    key_groups:
      - age:
          - *build01-ofborg-org
          - *hexa
          - *dasJ
          - *cole-h
          - *cole-h-2
  - path_regex: secrets/[^/]+.build02.ofborg.org.yml
    key_groups:
      - age:
          - *build02-ofborg-org
          - *hexa
          - *dasJ
          - *cole-h
          - *cole-h-2
